### PR TITLE
vendor: include gsm for phone

### PR DESCRIPTION
**Pull request by jjpprrrr**
otherwise APNs won't be built

### CODE REVIEW

**Comment by OdSazib** [comment]
> otherwise APNs won't be built

Add it to your device instead
```
# Inherit some common stuff from Project-Awaken
$(call inherit-product, vendor/awaken/config/common.mk)
$(call inherit-product, vendor/awaken/config/gsm.mk)

```

**Comment by jjpprrrr** [comment]
OK.

**Comment by jjpprrrr** [comment]
@saikiran2001 I saw that d43c8db8 starts to include gsm in common. What's the deal now? Did anything change?

**Comment by saikiran2001** [comment]
> @saikiran2001 I saw that [d43c8db](https://github.com/Project-Awaken/android_vendor_awaken/commit/d43c8db8f38c5569ed373c2d48d379716a24d8ca) starts to include gsm in common. What's the deal now? Did anything change?

Maintainers don't wanna include it in their trees so now including from common

**Pull request closed without merging**
